# coding=utf-8
from __future__ import unicode_literals
from django.utils.translation import ugettext as _
from model_utils import Choices

from openaid.crs.code_lists.donors import CodeName, Donor


AGENCIES = []

class Agency(CodeName):

    ALL = AGENCIES

    def __init__(self, code, name, acronym, donor, *args, **kwargs):
        super(Agency, self).__init__(code, name, *args, **kwargs)
        self.donor = Donor.get_by_code(donor)
        self.acronym = acronym

    @classmethod
    def get_all_by_donor(cls, donor):
        return [a for a in cls.get_all() if a.donor.code == donor]

def generate_data():
    # add agencies
    Agency(1, _('Federal Ministry of Finance'), 'BMF', 1)
    Agency(2, _('Various ministries'), 'MIN', 1)
    Agency(3, _('Federal Government of Austria'), 'BReg', 1)
    Agency(4, _('Oesterreichische Kontrollbank AG'), 'OeKB', 1)
    Agency(5, _('Federal Ministry for European and International Affairs '), 'BMeiA', 1)
    Agency(6, _('Provincial governments, local communities'), 'Reg', 1)
    Agency(7, _('Federal Chancellery'), 'BKA', 1)
    Agency(8, _('Austrian Development Agency'), 'ADA', 1)
    Agency(9, _('Education and Science Ministry'), 'BM/BWK', 1)
    Agency(10, _('Ministry for Agriculture and Environment'), 'BMLFUW', 1)
    Agency(11, _('Ministry of Defense'), 'BMLV', 1)
    Agency(12, _('Ministry of Interior'), 'BMI', 1)
    Agency(13, _('Austrian Development Bank'), 'OeEB', 1)
    Agency(14, _('Ministry for Education, Arts and Culture'), 'BM:UKK', 1)
    Agency(15, _('Ministry for Science and Research'), 'BMWF', 1)
    Agency(99, _('Miscellaneous'), 'MISC', 1)
    Agency(10, _('Directorate General for Co-operation and Development'), 'DGCD', 2)
    Agency(20, _('Official Federal Service of Foreign Affaires (excl. DGCD)'), 'SPAE', 2)
    Agency(30, _('Official Federal Service of Finance'), 'SPFF', 2)
    Agency(31, _('Ducroire National Office'), 'OND', 2)
    Agency(39, _('Other Official Federal Services'), 'ASPF', 2)
    Agency(70, _('Flanders Official Regional Ministries'), 'MPRF', 2)
    Agency(80, _('Walloon Official Regional Ministries'), 'MPRW', 2)
    Agency(91, _('Brussels Official Regional Ministries'), 'MPRB', 2)
    Agency(94, _('German speaking Official Regional Ministries'), 'MPRG', 2)
    Agency(99, _('Miscellaneous'), 'MISC', 2)
    Agency(1, _('Ministry of Foreign Affairs'), 'MFA', 3)
    Agency(2, _('Danish International Development Agency '), 'DANIDA', 3)
    Agency(72, _('Eksport Kredit Fonden'), 'EKR', 3)
    Agency(99, _('Miscellaneous'), 'MISC', 3)
    Agency(1, _('GOUV'), 'GOUV', 4)
    Agency(3, _('French Development Agency'), 'AFD', 4)
    Agency(6, _('Ministry of Foreign Affairs'), 'MAE', 4)
    Agency(8, _('COOP DECENTRALISED'), 'COOP DECENTRALISEE', 4)
    Agency(10, _('Ministry of Economy, Finance and Industry'), 'MINEFI', 4)
    Agency(12, _('Ministry of Interior'), 'Intérieur', 4)
    Agency(13, _('Ministry of Agriculture'), 'AGRI', 4)
    Agency(14, _('Ministry of Defense'), 'DEF', 4)
    Agency(15, _('Inter-ministerial'), 'INTER', 4)
    Agency(16, _('Other Ministries'), 'AUTRES', 4)
    Agency(17, _('Ministry of Higher education and Research'), 'MESR', 4)
    Agency(37, _('MIN/TRAVAIL'), 'MIN/TRAVAIL', 4)
    Agency(42, _('Banque de France'), 'MINEFI/BDF', 4)
    Agency(43, _('Coface'), 'Coface', 4)
    Agency(99, _('Miscellaneous'), 'MISC', 4)
    Agency(1, _('Bundesministerium für Wirtschaftliche Zusammenarbeit und Entwicklung'), 'BMZ', 5)
    Agency(2, _('Kreditanstalt für Wiederaufbau'), 'KFW', 5)
    Agency(4, _('German Investment and Development Company'), 'DEG', 5)
    Agency(5, _('Federal Ministry of Finance'), 'BMF', 5)
    Agency(7, _('Foreign Office'), 'F O', 5)
    Agency(9, _('Federal Ministry for the Env., Nature Conservation and Nuclear Safety'), 'BMU', 5)
    Agency(12, _('Federal States and Local Governments'), 'L G', 5)
    Agency(14, _('Federal Institutions'), 'Fed.Inst.', 5)
    Agency(15, _('Deutscher Entwicklungsdienst'), 'DED', 5)
    Agency(16, _('Federal Ministries'), 'Fed.Min.', 5)
    Agency(17, _('Foundations/Societies/Misc. (non federal)'), 'Found', 5)
    Agency(34, _('Euler Hermes Kreditversicherungs-AG'), 'Euler Hermes', 5)
    Agency(52, _('Deutsche Gesellschaft für Internationale Zusammenarbeit'), 'GIZ', 5)
    Agency(99, _('Miscellaneous'), 'MISC', 5)
    Agency(1, _('MGI'), 'MGI', 6)
    Agency(2, _('Agenzia Erogazioni Per l’Agricoltura'), 'AGEA', 6)
    Agency(3, _('OGPI'), 'OGPI', 6)
    Agency(4, _('Direzione Generale per la Cooperazione allo Sviluppo'), 'DGCS', 6)
    Agency(5, _('MC'), 'MC', 6)
    Agency(7, _('Central administration'), 'CA', 6)
    Agency(8, _('Local administration'), 'LA', 6)
    Agency(9, _('Artigiancassa'), 'Art.', 6)
    Agency(74, _('Sezione Speciale per l’Assicurazione del Credito all’Esportazione'), 'SACE', 6)
    Agency(99, _('Miscellaneous'), 'MISC', 6)
    Agency(1, _('Ministry of Foreign Affairs (DGIS)'), 'MFA', 7)
    Agency(3, _('NG'), 'NG', 7)
    Agency(4, _('NLD Gov. through NLD Inv Bank for Developing Countries'), 'NIO/FMO', 7)
    Agency(5, _('FMO'), 'FMO', 7)
    Agency(33, _('NCM Credit Management Worldwide'), 'NCM', 7)
    Agency(99, _('Miscellaneous'), 'MISC', 7)
    Agency(1, _('Norwegian Agency for Development Co-operation'), 'NORAD', 8)
    Agency(4, _('Ministry of Foreign Affairs'), 'MFA', 8)
    Agency(7, _('Innovation Norway'), 'IN', 8)
    Agency(8, _('NORFUND'), 'NORFUND', 8)
    Agency(9, _('FK Norway'), 'FK', 8)
    Agency(10, _('Office of the Auditor General'), 'OAG', 8)
    Agency(71, _('Garantiinstituttet for eksportkreditt'), 'GIEK', 8)
    Agency(99, _('Miscellaneous'), 'MISC', 8)
    Agency(1, _('Portuguese Government'), 'GP', 9)
    Agency(2, _('Institute for Portuguese Development Aid'), 'IPAD', 9)
    Agency(3, _('Municipalities'), 'MUNIC', 9)
    Agency(4, _('SOFID Sociedade para o Financiamento do Desenvolvimento'), 'SOFID Society for Development Financing', 9)
    Agency(71, _('Conselho de garantias financeiras'), 'COSEC', 9)
    Agency(99, _('Miscellaneous'), 'MISC', 9)
    Agency(1, _('SIDA'), 'SIDA', 10)
    Agency(2, _('Ministry of Foreign Affairs'), 'MFA', 10)
    Agency(3, _('SG'), 'SG', 10)
    Agency(4, _('SAREC'), 'SAREC', 10)
    Agency(5, _('BITS'), 'BITS', 10)
    Agency(6, _('Swedish International Development Authority'), 'Sida', 10)
    Agency(71, _('Swedish Export Credits Guarantee Board'), 'EKN', 10)
    Agency(99, _('Miscellaneous'), 'MISC', 10)
    Agency(1, _('Federal Administration (various departments)'), 'FA', 11)
    Agency(4, _('Swiss Agency for Development and Co-operation'), 'SDC', 11)
    Agency(5, _('State Secretariat for Economic Affairs'), 'Seco', 11)
    Agency(6, _('Federal Department of Foreign Affairs'), 'DFA', 11)
    Agency(7, _('State Secretariat for Education and Research'), 'SER', 11)
    Agency(8, _('Federal Office for Migration'), 'FOM', 11)
    Agency(9, _('Federal Department for Defence, Civil Protection and Sports'), 'DDPS', 11)
    Agency(10, _('Swiss Agency for the Environment, Forests and Landscape'), 'SAEFL', 11)
    Agency(11, _('Municipalities'), 'MUNIC', 11)
    Agency(99, _('Miscellaneous'), 'MISC', 11)
    Agency(1, _('Department for International Development'), 'DFID', 12)
    Agency(2, _('CDC Capital Partners PLC'), 'CDC', 12)
    Agency(3, _('Foreign & Commonwealth Office'), 'FCO', 12)
    Agency(4, _('Department of Energy and Climate Change'), 'DECC', 12)
    Agency(5, _('Export Credit Guarantee Department'), 'ECGD', 12)
    Agency(6, _('Home Office'), 'HO', 12)
    Agency(7, _('Department for Environment Food and Rural Affairs'), 'DEFRA', 12)
    Agency(8, _('Ministry of Defence'), 'MOD', 12)
    Agency(9, _('Department for Work and Pensions'), 'DWP', 12)
    Agency(10, _('Department of Health'), 'DH', 12)
    Agency(11, _('Department for Business, Innovation and Skills'), 'BIS', 12)
    Agency(12, _('Department for Culture, Media and Sports'), 'DCMS', 12)
    Agency(21, _('Scottish Government'), 'SG', 12)
    Agency(22, _('Welsh Assembly Government'), 'WAG', 12)
    Agency(99, _('Miscellaneous'), 'MISC', 12)
    Agency(1, _('Finnish Government'), 'FG', 18)
    Agency(2, _('FinnFund'), 'FF', 18)
    Agency(3, _('Ministry of Foreign Affairs'), 'MFA', 18)
    Agency(4, _('Other Ministries'), 'Other Min.', 18)
    Agency(72, _('FinnVera'), 'FinnVera', 18)
    Agency(99, _('Miscellaneous'), 'MISC', 18)
    Agency(1, _('Ministry of Foreign Affairs'), 'MFA', 20)
    Agency(2, _('ICEIDA'), 'ICEIDA', 20)
    Agency(3, _('ICRU'), 'ICRU', 20)
    Agency(1, _('Department of Foreign Affairs'), 'DFA', 21)
    Agency(2, _('Department of Finance'), 'DF', 21)
    Agency(3, _('Department of Agriculture, Food and the Marine'), 'DAFM', 21)
    Agency(99, _('Miscellaneous'), 'MISC', 21)
    Agency(1, _('Lux-Development'), 'LuxDev', 22)
    Agency(2, _('Ministry of Foreign Affairs'), 'MFA', 22)
    Agency(22, _('Ducroire Office'), 'ODL', 22)
    Agency(99, _('Miscellaneous'), 'MISC', 22)
    Agency(1, _('Ministry of the Interior'), 'MI', 40)
    Agency(2, _('Ministry of Finance'), 'MF', 40)
    Agency(3, _('Ministry of Foreign Affairs'), 'MFA', 40)
    Agency(4, _('Ministry of National Defense'), 'MND', 40)
    Agency(5, _('Ministry of Development, Competitiveness & Shipping'), 'MDCS', 40)
    Agency(6, _('Ministry of the Environment, Energy & Climate Change'), 'MEECC', 40)
    Agency(7, _('Ministry of Education, Life Long Learning & Religions'), 'MELLLR', 40)
    Agency(8, _('Ministry of Infrastructure, Transport and Networks'), 'MITN', 40)
    Agency(9, _('Ministry of Employment & Social Security'), 'MESS', 40)
    Agency(10, _('Ministry of Health & Social Solidarity'), 'MHSS', 40)
    Agency(11, _('Ministry of Agricultural Development & Food'), 'MADF', 40)
    Agency(12, _('Ministry of Justice, Transparency & Human Rights'), 'MJTHR', 40)
    Agency(13, _('Ministry of Citizen Protection'), 'MCP', 40)
    Agency(14, _('Ministry of Culture & Tourism'), 'MCT', 40)
    Agency(15, _('Municipalities'), 'LA', 40)
    Agency(99, _('Miscellaneous'), 'MISC', 40)
    Agency(1, _('Instituto de Credito Oficial'), 'ICO', 50)
    Agency(2, _('Compania Espanola de Seguros de Credito a la Exportacion'), 'CESCE', 50)
    Agency(4, _('Ministry of Agriculture, Fisheries, and Food'), 'AGR', 50)
    Agency(5, _('Ministry of Foreign Affairs and Co-operation'), 'MFA', 50)
    Agency(6, _('Ministry of Economy and Competitiveness'), 'ECON', 50)
    Agency(7, _('Ministry of Education, Culture and Sports'), 'EDUC', 50)
    Agency(8, _('Ministry of Public Works'), 'MPW', 50)
    Agency(9, _('Ministry of Industry and Energy'), 'MIE', 50)
    Agency(10, _('Ministry of the Environment and Rural and Marine Environs'), 'MARM', 50)
    Agency(11, _('Ministry of Health'), 'MOH', 50)
    Agency(12, _('Ministry of Labour and Social Affairs'), 'EMP', 50)
    Agency(13, _('Ministry of Interior'), 'INT', 50)
    Agency(14, _('Ministry of Public Administration'), 'MPA', 50)
    Agency(15, _('Autonomous Governments'), 'AG', 50)
    Agency(16, _('Municipalities'), 'MUNIC', 50)
    Agency(18, _('Ministry of Science and Technology'), 'MST', 50)
    Agency(19, _('Ministry of Defense'), 'DEF', 50)
    Agency(20, _('Public Universities'), 'UNIV', 50)
    Agency(21, _('Spanish Agency for International Development Co-operation'), 'AECID', 50)
    Agency(22, _('Others ministries'), 'Oth. Min.', 50)
    Agency(99, _('Miscellaneous'), 'MISC', 50)
    Agency(1, _('Czech Development Agency'), 'CZDA', 68)
    Agency(2, _('Ministry of Foreign Affairs'), 'MFA', 68)
    Agency(3, _('Ministry of Finance'), 'MOF', 68)
    Agency(4, _('Miinistry of Education, Youth, Sports'), 'MEYS', 68)
    Agency(5, _('Ministry of the Interior'), 'MOI', 68)
    Agency(6, _('Police'), 'Police', 68)
    Agency(7, _('Ministry of Defence'), 'MD', 68)
    Agency(8, _('Ministry of Health'), 'MH', 68)
    Agency(9, _('Ministry of Industry and Trade'), 'MIT', 68)
    Agency(10, _('Czech National Bank'), 'CNB', 68)
    Agency(11, _('Ministry of Justice'), 'MJ', 68)
    Agency(12, _('Ministry of Labour and Social Affairs'), 'MOLSA', 68)
    Agency(13, _('Universities'), 'Universities', 68)
    Agency(14, _('Regional Governments and Municipalities'), 'Regional Governments and Municipalities', 68)
    Agency(15, _('Ministry of Environment'), 'MOE', 68)
    Agency(16, _('State Office for Nuclear Saftey'), 'SUJB', 68)
    Agency(99, _('Other'), 'Other', 68)
    Agency(1, _('Canadian International Development Agency'), 'CIDA', 301)
    Agency(2, _('International Development Research Centre'), 'IDRC', 301)
    Agency(3, _('Department of Foreign Affairs, Trade and Development'), 'DFATD', 301)
    Agency(4, _('Department of Finance Canada'), 'FIN', 301)
    Agency(6, _('Foreign Affairs and International Trade Canada'), 'DFAIT', 301)
    Agency(7, _('Department of National Defence'), 'DND', 301)
    Agency(8, _('Royal Canadian Mounted Police of Canada'), 'RCMP', 301)
    Agency(9, _('Provincial Governments and municipalities'), 'GOV', 301)
    Agency(31, _('Export Development Canada'), 'EDC', 301)
    Agency(99, _('Miscellaneous'), 'MISC', 301)
    Agency(1, _('Agency for International Development'), 'AID', 302)
    Agency(2, _('Department of Agriculture'), 'AGR', 302)
    Agency(6, _('Department of Treasury'), 'DTRE', 302)
    Agency(7, _('Department of Defense'), 'DOD', 302)
    Agency(9, _('Department of the Interior'), 'INTERIOR', 302)
    Agency(10, _('Peace Corps'), 'PEACE', 302)
    Agency(11, _('State Department'), 'STATE', 302)
    Agency(12, _('Trade and Development Agency'), 'TDA', 302)
    Agency(13, _('African Development Foundation'), 'ADF', 302)
    Agency(14, _('Department of Health and Human Services'), 'HHS', 302)
    Agency(15, _('Department of Justice'), 'JUSTICE', 302)
    Agency(16, _('Department of Commerce'), 'COMMERCE', 302)
    Agency(17, _('Department of Labor'), 'LABOR', 302)
    Agency(18, _('Millennium Challenge Corporation'), 'MCC', 302)
    Agency(19, _('Department of Homeland Security'), 'DHS', 302)
    Agency(20, _('Department of Energy'), 'DOE', 302)
    Agency(21, _('Inter-American Development Foundation'), 'IADF', 302)
    Agency(22, _('Overseas Private Investment Corporation'), 'OPIC', 302)
    Agency(23, _('Federal Trade Commission'), 'FTC', 302)
    Agency(24, _('Nuclear Regulatory Commission'), 'NRC', 302)
    Agency(25, _('National Science Foundation'), 'NSF', 302)
    Agency(26, _('Department of Transportation'), 'DOT', 302)
    Agency(27, _('United States Institute of Peace'), 'USIP', 302)
    Agency(28, _('Open World Leadership Center'), 'LIC', 302)
    Agency(29, _('United States Postal Service'), 'POSTAL', 302)
    Agency(30, _('Executive Office of the President'), 'EOP', 302)
    Agency(31, _('Export Import Bank'), 'EXIM', 302)
    Agency(32, _('Environmental Protection Agency'), 'EPA', 302)
    Agency(33, _('Broadcasting Board of Governors'), 'BBG', 302)
    Agency(40, _('Private flows'), 'PRIVATE', 302)
    Agency(99, _('Miscellaneous'), 'MISC', 302)
    Agency(1, _('Kuwait Fund for Arab Economic Development'), 'KFAED', 552)
    Agency(2, _('Government Grants administered by KFAED KFAED'), '', 552)
    Agency(99, _('Miscellaneous'), 'MISC', 552)
    Agency(2, _('Abu Dhabi Department of Finance'), 'DOF', 576)
    Agency(3, _('Abu Dhabi Fund for Development'), 'ADFD', 576)
    Agency(7, _('International Humanitarian City'), 'IHC', 576)
    Agency(17, _('Khalifa Bin Zayed Al Nahyan Foundation'), 'KZF', 576)
    Agency(18, _('Mohammed Bin Rashid Al Maktoum Humanitarian and Charity Establishment'), 'MRHC', 576)
    Agency(19, _('Zayed Bin Sultan Al Nahyan Charitable and Humanitarian Foundation'), 'ZCHF', 576)
    Agency(20, _('Al Maktoum Foundation'), 'MF', 576)
    Agency(21, _('Dubai Cares'), 'DC', 576)
    Agency(22, _('UAE Red Crescent Authority'), 'RCA', 576)
    Agency(23, _('Noor Dubai'), 'ND', 576)
    Agency(25, _('Other Government Entitites'), 'OTHER', 576)
    Agency(99, _('Miscellaneous'), 'MISC', 576)
    Agency(1, _('Ministry of Agriculture, Forestry and Fisheries'), 'MAFF', 701)
    Agency(2, _('Ministry of Foreign Affairs'), 'MOFA', 701)
    Agency(4, _('EXIM BANK'), 'EXIM BANK', 701)
    Agency(5, _('OECF'), 'OECF', 701)
    Agency(6, _('FOOD AID'), 'FOOD AID', 701)
    Agency(7, _('Overseas Fishery Co-operation Foundation'), 'OFCF', 701)
    Agency(8, _('Japanese International Co-operation Agency'), 'JICA', 701)
    Agency(10, _('Japan Overseas Development Co-operation'), 'JODC', 701)
    Agency(11, _('Japan Bank for International Co-operation'), 'JBIC', 701)
    Agency(12, _('Other Ministries'), 'Oth. MIN', 701)
    Agency(13, _('Public Corporations'), 'PC', 701)
    Agency(14, _('Prefectures'), 'PRF', 701)
    Agency(15, _('Ordinance-designed Cities'), 'ODC', 701)
    Agency(71, _('Nippon Export and Investment Insurance'), 'NEXI', 701)
    Agency(99, _('Miscellaneous'), 'MISC', 701)
    Agency(1, _('Ministry of Strategy and Finance'), 'MOSF', 742)
    Agency(2, _('Export-Import Bank of Korea'), 'KEXIM', 742)
    Agency(3, _('Ministry of Foreign Affairs and Trade'), 'MOFAT', 742)
    Agency(4, _('Korea International Cooperation Agency'), 'KOICA', 742)
    Agency(99, _('Miscellaneous'), 'MISC', 742)
    Agency(2, _('Attorney-General'), 'AG', 801)
    Agency(5, _('Australian government'), 'Aus Gov', 801)
    Agency(72, _('Export Finance and Insurance Corporation'), 'EFIC', 801)
    Agency(99, _('Miscellaneous'), 'MISC', 801)
    Agency(1, _('Ministry of Foreign Affairs and Trade'), 'NZG', 820)
    Agency(2, _('New Zealand International Aid and Development Agency'), 'NZAid', 820)
    Agency(99, _('Miscellaneous'), 'MISC', 820)
    Agency(1, _('Commission of the European Communities'), 'CEC', 918)
    Agency(2, _('European Development Fund'), 'EDF', 918)
    Agency(3, _('European Investment Bank'), 'EIB', 918)
    Agency(4, _('Humanitarian Aid Office of the European Commission'), 'ECHO', 918)
    Agency(99, _('Miscellaneous'), 'MISC', 918)
    Agency(1, _('Bill & Melinda Gates Foundation'), '', 1601)

generate_data()